name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - name: Build 11ty Site
        run: npx @11ty/eleventy
        env:
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
#      - uses: bahmutov/npm-install@v1
#        with:
#          useLockFile: false
#      - name: Build
#        uses: TartanLlama/actions-eleventy@v1.1
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v1.1.0
#        env:
#          PUBLISH_DIR: _site 
#          PUBLISH_BRANCH: gh-pages
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "_site/*"
          target: "/home/palousemutualaid/palousemutualaid.com"
          strip_components: 1

